### ISSUE TITLE
Add `rnr` to Homebrew

### ISSUE THREAD

**Issue by Miserlou** [ismaelgv/rnr#25]
Excellent tool, would be great to have it available in Homebrew!

**Comment by ismaelgv** [comment]
Thanks @Miserlou! I have no experience with Homebrew nor access to a MacOS system.

Any contribution will be more than welcome.

**Comment by ivaquero** [comment]
Hi, @ismaelgv, I'm trying to create a Homebrew script, but failed

The file is 

```ruby
class Rnr < Formula
  desc "Command-line tool to batch rename files and directories"
  homepage "https://github.com/ismaelgv/rnr"
  url "https://github.com/ismaelgv/rnr/archive/refs/tags/v0.4.1.tar.gz"
  sha256 "85013be46725acc1cd6f2d2089c42f426c052efab26d22db8a9f28051eebbb6a"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", *std_cargo_args
    generate_completions_from_executable(bin/"rnr", "gen_completions", base_name: "rnr")
  end

  test do
    # Check that a typical Conventional Commit is considered correct.
    system "git", "init"
    (testpath/"some-file").write("")
    system "git", "add", "some-file"
    system "git", "config", "user.name", "'Ismael González Valverde'"
    system "git", "config", "user.email", "ismgonval@gmail.com"
    system "git", "commit", "-m", "chore: initial commit"
    assert_equal "No errored commits", shell_output("#{bin}/rnr check 2>&1").strip
  end
end
```

The error message is

```console
Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/rnr/0.4.1/bin/rnr gen_completions bash` exited with 1. Here's the output:
```

This is the result of wrong command of `generate_completions` functionality, then what is the exact command ?

**Comment by ismaelgv** [comment]
Thanks for trying to pack RnR for Homebrew. I got no experience with that package manager, but I will take a look at the problem of the completion generation as soon as possible.

**Comment by ismaelgv** [comment]
@ivaquero I think that you do not need to generate anything manually. The completion files are generated when you build the project, not with any additional command. You would need to package the completions.


You can take a look to [`bat` formulae](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bat.rb) to use it as reference.

You can also check the current CI/CD configuration that generates the release:
https://github.com/ismaelgv/rnr/blob/master/.github/workflows/release.yml#L67-L105

**Comment by ivaquero** [comment]
Good suggestion. I will look into it.

**Comment by ivaquero** [comment]
For now, the script can successfully be built

```ruby
class Rnr < Formula
  desc "Command-line tool to batch rename files and directories"
  homepage "https://github.com/ismaelgv/rnr"
  url "https://github.com/ismaelgv/rnr/archive/refs/tags/v0.4.1.tar.gz"
  sha256 "85013be46725acc1cd6f2d2089c42f426c052efab26d22db8a9f28051eebbb6a"
  license "MIT"

  depends_on "rust" => :build

  def install
    ENV["SHELL_COMPLETIONS_DIR"] = buildpath
    system "cargo", "install", *std_cargo_args

    deploy_dir = Dir["target/release/build/rnr-*/out"].first
    bash_completion.install "#{deploy_dir}/rnr.bash" => "rnr"
    fish_completion.install "#{deploy_dir}/rnr.fish"
    # zsh_completion.install "#{deploy_dir}/rnr.zsh" => "rnr"
  end

  test do
  end
end
```

```console
❯ rnr -h
rnr 0.4.1
Ismael González Valverde <ismgonval@gmail.com>
RnR is a command-line tool to rename multiple files and directories that
supports regular expressions

USAGE:
    rnr [FLAGS] [OPTIONS] <EXPRESSION> <REPLACEMENT> <PATH(S)>...
    rnr [FLAGS] [OPTIONS] <SUBCOMMAND>
....
```

However, there are several missing parts

- [ ] zsh_completion, the CI doesn't include zsh
- [ ] test function, I am not sure the best way to test rnr

**Comment by ismaelgv** [comment]
> zsh_completion, the CI doesn't include zsh

The CI is generating the ZSH completion, but the file is called `_rnr`. You need to correct that in the script.


> test function, I am not sure the best way to test rnr, I wonder whether to use the previous one

All the testing is running in the CI system of the project (Github Actions). I am not sure why it is needed to be run in the Homebrew again.

**Comment by ivaquero** [comment]
I added the ZSH completion

```ruby
  def install
    ENV["SHELL_COMPLETIONS_DIR"] = buildpath
    system "cargo", "install", *std_cargo_args

    deploy_dir = Dir["target/release/build/rnr-*/out"].first
    bash_completion.install "#{deploy_dir}/rnr.bash" => "rnr"
    fish_completion.install "#{deploy_dir}/rnr.fish"
    zsh_completion.install "#{deploy_dir}/rnr.zsh" => "_rnr"
  end
```

But the output says the file can't be found

```console
==> cargo install
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - target/release/build/rnr-2eb49c625afc7ce62/out/rnr.zsh
```

**Comment by ivaquero** [comment]
Okay, it works, I will check what to put in test section.

**Comment by ismaelgv** [comment]
@ivaquero I think you need to copy ZSH completion file as it is `_rnr`, you are renaming it to `rnr`.

If you want to test something you may want to rename a dummy file. For example, the `bat` example is just checking that the CLI tool is functional printing the content of a file.

**Comment by ivaquero** [comment]
No problem, I will try.

I suggest that you create a new repo to host this Homebrew script and mention it in the README, because Homebrew official has a relatively strict standard, we need more time and users to test to avoid the PR to be closed accidentally.

**Comment by ismaelgv** [comment]
Feel free to host it yourself until it is merged to Homebrew official repository. I cannot provide proper support to that script since I cannot test it. However, you can maintain it if it is fine for you.

I will add the information to the README.md once it is ready.

Thanks for your contribution to the project! 😉

**Comment by ivaquero** [comment]
A PR has been made: https://github.com/Homebrew/homebrew-core/pull/115749

**Comment by ismaelgonval** [comment]
@ivaquero I see that they approved the PR, thanks for the contribution! I will add the information to the `README.md`.

**Comment by ivaquero** [comment]
You are welcome. Thank you for this helpful tool.

**Comment by ivaquero** [comment]
The PR has been merged! This issue can be closed.

**Comment by ismaelgv** [comment]
I will update the readme before closing this issue. I am a bit busy these days so it may take me some time. Thanks!
