### ISSUE TITLE
Confirming cli app only

### ISSUE THREAD

**Issue by d0e8414e** [ismaelgv/rnr#27]
Hello!

Thanks for a great tool.  I have an mp3 library I'm trying to wrangle into consistency and rnr has smoothed that path quite nicely.  I especially appreciate undo file/dry-run by default.

Anyway, I think it's not possible, but can rnr be incorporated into another rust app via a crate dependency, i.e. is there an api implementation for rnr?  Or is the only option to use rnr from within a rust program to call rnr via std process Command?

Thanks!

**Comment by ismaelgv** [comment]
I'm glad that this tool is useful to you. ;)

Currently, this tool is only working as a CLI. However, I was planning to separate the core so it could be integrated in other interfaces (p.e. TUI, GTK UI, ...).

What functionality would be useful to be exposed for  your use case?

**Comment by d0e8414e** [comment]
I'll let you know if I think of anything.  I've found it intuitive to use when I have.  Thanks!
