### ISSUE TITLE
Possible to rename only directories and not files?

### ISSUE THREAD

**Issue by iTwenty** [ismaelgv/rnr#33]
Hello, thanks for making this wonderful little tool!

I have a scenario where I have a bunch of directories, and each directory has files with same name as directory, but different extensions. Example -

```
├── X Men - Apocalypse (2016) (720p)
│   ├── X Men - Apocalypse (2016) (720p).mp4
│   └── X Men - Apocalypse (2016) (720p).srt
├── X Men - Days Of Future Past (2014) (720p)
│   ├── X Men - Days Of Future Past (2014) (720p).mp4
│   └── X Men - Days Of Future Past (2014) (720p).srt
├── X Men - First Class (2011) (720p)
│   ├── X Men - First Class (2011) (720p).mp4
│   └── X Men - First Class (2011) (720p).srt
```

I only want to rename the directories, but not the files inside. Is this possible with rnr? Going through the help page, it doesn't look like rnr supports this, but wanted to confirm.

**Comment by ismaelgv** [comment]
Well, you got several options here depeding on what you want to do. I hope any of the following suggestion works for you.

----

For the sake of making an example, suppose we want to rename directories from `film` to `rename-film` in the following directory tree:
![image](https://github.com/ismaelgv/rnr/assets/8478202/53e56903-3d82-4fd2-8daf-d9c2cf532253)

### Do not use recursive option
If you are just in a directory that only contains directories you can use:
```bash
rnr -D 'film' 'renamed-film' ./*
```
This way you just rename the directories and files in the current directory without taking in to account the content of each directory.

More info in this section of the documentation:
https://github.com/ismaelgv/rnr#include-directories

### Use regular expression
Use the powerful regular expression system to make sure you are taking only the directories if you are using the recursive option:
```bash
rnr -Dr 'film-(\d)$' 'rename-film-$1' .
```
Just note that the first regular expression forces the source name to finish (`$` symbol) with `film-` and a digit (`\d`). We capture the digit and use it in the replacement with `$1`.

This will rename it correctly even if you got nested directory structure. Just try to find a proper regular expression for your case.

More info in this section of the documentation:
https://github.com/ismaelgv/rnr#capture-groups

### Use an external tool
Use an external tool to just take the directories if you want a robust and flexible approach if you have a non-regular nested directory structure:
```bash
find . -type d | xargs rnr -Dr 'film' 'renamed-film'
```
In this case we just use `find` UNIX tool, but you could also do this with other like [`fd`](https://github.com/sharkdp/fd) or similar CLI tools. Here we are just picking files of type directory and passing them as arguments to `rnr` to be rename.
 
More info in this section of the documentation:
https://github.com/ismaelgv/rnr#combination-with-other-unix-tools

**Comment by iTwenty** [comment]
@ismaelgv Thanks! I forgot I could always pipe the output of external tools to rnr. Marking this as closed.
