### ISSUE TITLE
send argument to another command to do some string manipulation operation

### ISSUE THREAD

**Issue by blueray453** [ismaelgv/rnr#34]
This is related to https://github.com/ismaelgv/rnr/issues/32

It would nice to be able to send argument to another command to do some operation. For example:

    rnr -f -D "(.*)" (ccase -t Kebab "$1") (fd --type d)

to change the case of files. Here [ccase](https://github.com/rutrum/convert-case)  in another rust tool.

**Comment by ismaelgv** [comment]
Thanks for opening this issue. It sounds like a nice idea, but I think this is a bit out of scope of this project by now. 

This project is not ment to support complex processing directives nor execute other binaries in the system. I want to keep it relatively simple and composable without any external dependency.

You always can achieve this piping the output to other commands (or receiving inputs) like shown in the documentation. For more complex use cases, you can always create a JSON with the desired operations and run it from RnR.

About the other issue you linked, I think it will handle it in a more restricted way.
