### ISSUE TITLE
[feature request] can provide a parameter to save the historical naming replacement rules

### ISSUE THREAD

**Issue by bindiry** [ismaelgv/rnr#39]
can provide a parameter to save the historical naming replacement rules

and can give this rule a name.

which I find very useful. :)

Thank you to developed this tools, I love it. 🥰

**Comment by ismaelgv** [comment]
Thanks @bindiry, I'm glad you find this tool useful.

I am not sure if I understood your request correctly. If you want to repeat previous command or handle your history, it may be better to use just other tools in your shell. For example:
* Creating aliases
* Wrapping `rnr` in a custom script
* Using utilities that handle arbitrary command history (e.g. zsh-history-substring-search)

**Comment by ismaelgv** [comment]
Feel free to open it again if these suggestions do not solve your problem.
