### ISSUE TITLE
--force option not working for to-ascii on Windows. Not renaming the files.

### ISSUE THREAD

**Issue by NameDevRandom** [ismaelgv/rnr#41]
Hi all,

```
rnr --force --no-dump to-ascii "UDTEAL - 해상고속기동.mp3" 
This is a DRY-RUN
UDTEAL - 해상고속기동.mp3 -> UDTEAL - HaeSangGoSogGiDong.mp3
```

does not rename anything and leads to the same result as

```
rnr --dry-run --no-dump to-ascii "UDTEAL - 해상고속기동.mp3" 
This is a DRY-RUN
UDTEAL - 해상고속기동.mp3 -> UDTEAL - HaeSangGoSogGiDong.mp3
```
Tested on Windows 11 using releases v0.4.2, v0.4.1, and v0.4.0 with both msvc and gnu builds.

Other operations like
`rnr --force -r foo bar . `
are working just fine.

Kindly check and fix this bug.

Best regards

**Comment by ismaelgv** [comment]
@NameDevRandom thanks for the report. I will take a look as soon as possible.

**Comment by ismaelgv** [comment]
I cannot reproduce this bug in Linux, I will try to test it in a Windows system as soon as possible.
